[build]
  command = "bun install && bun run build --filter=ppanel-user-web"
  publish = "apps/user/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://api.ppanel.dev/:splat"
  status = 200
  force = false

# SPA 路由支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
